<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Currency;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{
    //mise à jour des taux avec la commande
    public function updateExchangeRate($rates)
    {

        $results = [];

        foreach ($rates as $key => $value){
            $results[] = $this
                ->getEntityManager()
                ->createQueryBuilder()
                ->update(Currency::class, 'exchangeRate')
                ->set('exchangeRate.rate' , ':value') //on écrit comme ça car c'est un objet
                ->where('exchangeRate.base = :currency')
                ->setParameters([
                    'value' => $value,
                    'currency' => $key

                ])
                ->getQuery()
                ->execute()
            ;
        }

        return count($results);
    }

}
