<?php

namespace AppBundle\Repository;

use AppBundle\Entity\UserToken;

/**
 * UserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTokenRepository extends \Doctrine\ORM\EntityRepository
{
    //mise à jour des taux avec la commande
    public function deleteExpiredTokens()
    {
        $results = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->delete(UserToken::class, 'usertoken')
            ->where('usertoken.expirationDate < NOW()')
            ->getQuery()
            ->execute();
    }

}
